---
# tasks file for setup-docker
- name: Install dependies
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes

- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
    update_cache: yes

- name: Install docker engine
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  notify: restart docker
